### ISSUE TITLE
Script returns no data after re-running it

### ISSUE THREAD

**Issue by Mega-Barrel** [israel-dryer/Twitter-Scraper#10]
I followed your tutorial for scraping the Twitter data, as the script was running, after few minutes it returned the following exception/error message

_TimeoutException: Message: timeout: Timed out receiving a message from renderer: 300.000 (Session info: MicrosoftEdge=93.0.961.38)_ and returned around 2700 tweets data.

Running the script again after some time it returned **No data/0**.
![image](https://user-images.githubusercontent.com/34334153/132973295-fb4d690c-752f-435f-8b4e-c57aa343a282.png)

OS: Windows 10 Home
Browser: Microsoft Edge
Web-driver: Version: 93.0.961.47 | x64
Editor: VS Code

**Comment by b4rlw** [comment]
I was having the same problem tonight, but I think I've found the root of the issue.
It appears that Twitter has made some changes to the website, and changed a crucial `<div>` tag to an `<article>` tag.

Up until now, under the `collect_all_tweets_from_current_view` function, the line was:
`page_cards = driver.find_elements_by_xpath('//div[@data-testid="tweet"]')`

My script started working again when I changed this line to:
`page_cards = driver.find_elements_by_xpath('//article[@data-testid="tweet"]')`

Hope this helps.

**Comment by Mega-Barrel** [comment]
Thanks for your help, do you have any idea how to convert _2021-08-28T23:55:34.000Z_ into a date-time. because on the Twitter card, it shows Aug 29.
![image](https://user-images.githubusercontent.com/34334153/133197496-620ad09d-c160-4cf3-a0ff-70360e524925.png)

**Comment by Mega-Barrel** [comment]
I tried with the following code, but the problem is that on the Twitter card the date displays _Aug 29_ and from my code below it gives _Aug 28_

**Code**

```python
import datetime

d2 = datetime.datetime.strptime("2021-08-28T23:55:34.000Z","%Y-%m-%dT%H:%M:%S.%fZ")
new_format = "%Y-%m-%d"
d2.strftime(new_format)
print(d2)
```

**Output**
2021-08-28 23:55:34

**Comment by b4rlw** [comment]
I'm probably not the best person to ask about the subtleties of timezones and how Twitter interprets them, but I'd sooner trust the information in the full string rather than the short text.
I think that the string is always in UTC, and the short text typically shows how long ago a tweet has been made, ie. 3m, 4h, 1d etc. Could be that Twitter is rounding up, I'm not sure.

**Comment by Mega-Barrel** [comment]
Ooh, I got the solution to convert to specific time zones. Basically, the timestamp we are getting using selenium is in **Zulu** format. 
I used the following code to convert to local timezones

**Code**
``` python
import datetime

d2 = datetime.datetime.strptime("2021-08-28T09:52:48.000Z","%Y-%m-%dT%H:%M:%S.%fZ")
new_format = "%Y-%m-%d"
d2.strftime(new_format)
print(d2)
```

**Output**
```
2021-08-28 09:52:48
```

And 

``` python
import calendar
import time

time_tuple = time.strptime("2021-08-28 23:55:34", "%Y-%m-%d %H:%M:%S")
t = calendar.timegm(time_tuple)
print(time.ctime(t))
```

**Output**
```
Sun Aug 29 05:25:34 2021
```

The above code is not that optimized
