### ISSUE TITLE
If twitter user posted a poll, it seems to stop scrolling

### ISSUE THREAD

**Issue by Caitlan** [israel-dryer/Twitter-Scraper#2]
I think title explains it all, but I was running it for Apple tweets, and when I hit a poll it stopped scrolling. I was able to replicate the issue. If you search "#Apple", it's a tweet on Nov 25th by eranga that kills it for me. I believe the poll is causing it, but I am not positive.

**Comment by Caitlan** [comment]
Might be a twitter thing actually. Or a "me" issue lol.

**Comment by Caitlan** [comment]
Actually, I regret closing this. It seems like you can get it to work by manually scrolling up and down a few times. Again, it might just be a personal isssue with this. I am going to try to fix it for myself by including something to scroll up to the top of the page and back down if it stops scrolling, then try again.

Edit: I resolved this issue for myself by adding the following code after scroll_attempt +=1
            driver.execute_script("return window.scrollBy(0,-1350);")           
            sleep(2)
            driver.execute_script("return window.scrollBy(0,-1350);")
            sleep(2)
            driver.execute_script("return window.scrollBy(0, 1350);")
            sleep(2)
            driver.execute_script("return window.scrollBy(0, 1350);")
            sleep(2)
            driver.execute_script("return window.scrollBy(0, 350);")

Essentially my goal was to have it scroll up a bit and scroll back down, simulating a person actually scrolling up and down a bit. I tried lower numbers at first but needed to increase them. This allowed me to get past any posts that would stop me and I was able to get 30 days worth of data before manually stopping it. Additionally, I saw the orignal issue occur a few times on posts that were not polls. I'm not sure why it happened, but making it scroll up a bit and down again seemed to work for me. I am very new to python and even newer to anything selenium related, so if what I've done above could cause any errors, please feel free to let me know. Thank you very much to the original creater of this code!!

**Comment by israel-dryer** [comment]
I've been making some adjustments lately to the script. I think the script may now work fine in your situation. But, let me know if this persists.

**Comment by israel-dryer** [comment]
https://github.com/israel-dryer/Twitter-Scraper/blob/main/twitter_scraper.py

**Comment by Caitlan** [comment]
Thank you :)!!
