### ISSUE TITLE
Not pulling all tweets

### ISSUE THREAD

**Issue by senanabs** [israel-dryer/Twitter-Scraper#3]
This is a great tool and thank you for sharing it. I came across an issue where it's not pulling all tweets. For example, I used search term "#HummerEV". On 10/20/2020, there were 67 total tweets with that hash tag. However, the script only returns 46 tweets. I used different number of tweets to look over (30 instead of 15) and I changed the number of seconds to 3 from 1. Any insight is appreciated.

Thanks

**Comment by israel-dryer** [comment]
One of the reasons that this could be happening is that I'm excluding anything that doesn't have a postdate... which usually means that it's promoted content. You can fix this by adjusting the code below to set a default value.
```python.
    try:
        postdate = card.find_element(By.XPATH, './/time').get_attribute('datetime')
    except NoSuchElementException:  # promoted content
        return
```

**Comment by senanabs** [comment]
Thanks for the response. When you say content that doesn't have a postdate, you mean any tweet without a date next to the twitter handle (such as ads), correct? Because I also didn't count those when I manually counted tweets. 

Do you think this could be because the pages are refreshing too fast for the script to scrape tweets? I changed the number of seconds to wait to 5 seconds with no improvement.

**Comment by israel-dryer** [comment]
I've made some changes to the script that I believe fixes this problem: https://github.com/israel-dryer/Twitter-Scraper/blob/main/twitter_scraper.py
