### ISSUE TITLE
I didn't get any tweet

### ISSUE THREAD

**Issue by adeariniputri** [israel-dryer/Twitter-Scraper#4]
I watched your tutorial from youtube. When I tried to run the code the same exactly like your tutorial, it didn't work. So I came here to your github repository and run it on my jupyter notebook. I had all the requirements before I run the code like what you've suggested on your youtube tutorial. But it didn't pull out any tweet. Can you help me with this issue?
Thanks again for the tutorial!

**Comment by israel-dryer** [comment]
I've updated the script to work out some of the bugs. check this version out. I think it will fix your issues. https://github.com/israel-dryer/Twitter-Scraper/blob/main/twitter_scraper.py
