### ISSUE TITLE
Stale element error

### ISSUE THREAD

**Issue by finashort** [israel-dryer/Twitter-Scraper#8]
I have run this twitter scraping code with success a few times and am now running into the below error. Wondering what thoughts you might have on this:

StaleElementReferenceException: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=91.0.4472.77)

**Comment by israel-dryer** [comment]
I've updated since of these projects here.
https://github.com/israel-dryer/Web-Scraping-Projects

**Comment by MrCsabaToth** [comment]
What's the reason for such exception though?
